"""Factual Switch save catalogue, not copied editor implementation.

Offsets/names independently transcribed from EdiZon Config 0100F15003E64000
(CrisFTW/Brawl345) and GBATemp Switch research thread505591/neomy2 v0.5.1.
Those projects disclose no located licence; no program code or assets are reused.
See docs/FIRE_EMBLEM_WARRIORS_FORMAT.md for source/qualification restrictions.
"""
MATERIALS = ((64568, "Rowan's Buckle"),
 (64570, "Rowan's Cape"),
 (44, "Lianna's Hairpin"),
 (46, "Lianna's Cape"),
 (48, "Chrom's Leather Belt"),
 (50, "Chrom's Pauldron"),
 (52, "Lucina's Cuffs"),
 (54, "Lucina's Mask"),
 (56, "Robin's Primer"),
 (58, "Robin's Robes"),
 (60, "Lissa's Nest-Egg Purse"),
 (62, "Lissa's Crinoline"),
 (64, "Frederick's Pebbles"),
 (66, "Frederick's Ribbon Tie"),
 (68, "Cordelia's Wing Hairpins"),
 (70, "Cordelia's Book on Love"),
 (72, "Owain's Belt Sash"),
 (74, "Owain's Divine Names"),
 (76, "Corrin's Brooch"),
 (78, "Corrin's Hair Clasp"),
 (80, "Ryoma's Headpiece"),
 (82, "Ryoma's Battle Coat"),
 (84, "Hinoka's Tassels"),
 (86, "Hinoka's Scarf"),
 (88, "Takumi's History Book"),
 (90, "Takumi's Fur Wrap"),
 (92, "Sakura's Sash"),
 (94, "Sakura's Headband"),
 (96, "Oboro's Sleeve Sash"),
 (98, "Oboro's Chest Guard"),
 (100, "Xander's Shield"),
 (102, "Xander's Plate Armor"),
 (104, "Camilla's Belt"),
 (106, "Camilla's Tasses"),
 (108, "Leo's Tomato"),
 (110, "Leo's Collar"),
 (112, "Elise's Flowers"),
 (114, "Elise's Ribbon"),
 (116, "Niles's Hood"),
 (118, "Niles's Eye Patch"),
 (120, "Marth's Brooch"),
 (122, "Marth's Tiara"),
 (124, "Caeda's Bracelet"),
 (126, "Caeda's Breastplate"),
 (128, "Navarre's Cord Belt"),
 (130, "Navarre's Sword Strap"),
 (132, "Tiki's Anklet"),
 (134, "Tiki's Hairpin"),
 (136, "Celica's Shield"),
 (138, "Celica's Circlet"),
 (140, "Lyn's Glove"),
 (142, "Lyn's Cord Belt"),
 (144, "Anna's Cap"),
 (146, "Anna's Purse"),
 (148, "Validar's Bracelet"),
 (150, "Validar's Necklace"),
 (152, "Iago's Dark Instrument"),
 (154, "Iago's Half Mask"),
 (156, "Gharnef's Ring"),
 (158, "Gharnef's Orb"),
 (160, "Darios's Shield"),
 (162, "Darios's Circlet"),
 (164, "Chaos Dragon's Barbs"),
 (166, "Chaos Dragon's Jewel"),
 (168, "Myrmidon's Breechcloth"),
 (170, "Myrmidon's Head Guard"),
 (172, "Soldier's Waist Guard"),
 (174, "Soldier's Helmet"),
 (176, "Axe Fighter's Glove"),
 (178, "Axe Fighter's Helmet"),
 (180, "Archer's Breastplate"),
 (182, "Archer's Shoulder Pad"),
 (184, "Mage's Mask"),
 (186, "Mage's Robe"),
 (188, "Outlaw's Bracer"),
 (190, "Outlaw's Mask"),
 (192, "Knight's Shield"),
 (194, "Knight's Pauldron"),
 (196, "Cavalier's Greaves"),
 (198, "Cavalier's Saddle"),
 (200, "Pegasus Knight's Down"),
 (202, "Pegasus Knight's Visor"),
 (204, "Wyvern Rider's Talon"),
 (206, "Wyvern Rider's Tasses"),
 (208, "Great Knight's Gauntlet"),
 (210, "Great Knight's Barding"),
 (212, "Manakete's Scale"),
 (214, "Manakete's Tail"),
 (216, "Monster's Fang"),
 (218, "Monster's Horns"),
 (220, "Captain's Sword"),
 (222, "Captain's Lance"),
 (224, "Captain's Axe"),
 (226, "Captain's Bow"),
 (228, "Captain's Tome"),
 (230, "Monster's Claw"),
 (232, "Enliron's Scroll"),
 (234, "Facinna's Scroll"),
 (236, "Falchion's Scroll"),
 (238, "Parallel Falchion's Scroll"),
 (240, "Thoron's Scroll"),
 (242, "Lissa's Axe's Scroll"),
 (244, "Frederick's Axe's Scroll"),
 (246, "Cordelia's Lance's Scroll"),
 (248, "Missiletainn's Scroll"),
 (250, "Yato's Scroll"),
 (252, "Raijinto's Scroll"),
 (254, "Hinoka's Scroll"),
 (256, "Fujin Yumi's Scroll"),
 (258, "Spellbane Yumi's Scroll"),
 (260, "Oboro's Spear's Scroll"),
 (262, "Siegfried's Scroll"),
 (264, "Camilla's Axe's Scroll"),
 (266, "Brynhildr's Scroll"),
 (268, "Moonlight's Scroll"),
 (270, "Niles's Bow's Scroll"),
 (272, "Exalted Falchion's Scroll"),
 (274, "Wing Spear's Scroll"),
 (276, "Wo Dao's Scroll"),
 (278, "Divinestone's Scroll"),
 (280, "Lady Sword's Scroll"),
 (282, "Sol Katti's Scroll"),
 (284, "Anna's Bow's Scroll"),
 (286, "Rowan's Essence"),
 (288, "Lianna's Essence"),
 (290, "Chrom's Essence"),
 (292, "Lucina's Essence"),
 (294, "Robin's Essence"),
 (296, "Lissa's Essence"),
 (298, "Frederick's Essence"),
 (300, "Cordelia's Essence"),
 (302, "Owain's Essence"),
 (304, "Corrin's Essence"),
 (306, "Ryoma's Essence"),
 (308, "Hinoka's Essence"),
 (310, "Takumi's Essence"),
 (312, "Sakura's Essence"),
 (314, "Oboro's Essence"),
 (316, "Xander's Essence"),
 (318, "Camilla's Essence"),
 (320, "Leo's Essence"),
 (322, "Elise's Essence"),
 (324, "Niles's Essence"),
 (326, "Marth's Essence"),
 (328, "Caeda's Essence"),
 (330, "Navarre's Essence"),
 (332, "Tiki's Essence"),
 (334, "Celica's Essence"),
 (336, "Lyn's Essence"),
 (338, "Anna's Essence"),
 (340, "Azura's Opera Gloves"),
 (342, "Azura's Pendant"),
 (344, "Blessed Lance's Scroll"),
 (346, "Azura's Essence"),
 (348, "Yato's Opus"),
 (350, "Raijinto's Opus"),
 (352, "Hinoka's Lance's Opus"),
 (354, "Fujin Yumi's Opus"),
 (356, "Spellbane Yumi's Opus"),
 (358, "Oboro's Lance's Opus"),
 (360, "Siegfried's Opus"),
 (362, "Camilla's Axe's Opus"),
 (364, "Brynhildr's Opus"),
 (366, "Moonlight's Opus"),
 (368, "Niles's Bow's Opus"),
 (370, "Blessed Lance's Opus"),
 (372, "Linde's Bangle"),
 (374, "Linde's Charm"),
 (376, "Linde's Essence"),
 (378, "Aura's Scroll"),
 (380, "Minerva's Whip"),
 (382, "Minerva's Red Armor"),
 (384, "Minerva's Essence"),
 (386, "Hauteclere's Scroll"),
 (388, "Enliron's Opus"),
 (390, "Facinna's Opus"),
 (392, "Exalted Falchion's Opus"),
 (394, "Wing Spear's Opus"),
 (396, "Divinestone's Opus"),
 (398, "Lady Sword's Opus"),
 (400, "Sol Katti's Opus"),
 (402, "Anna's Bow's Opus"),
 (404, "Wo Dao's Opus"),
 (406, "Aura's Opus"),
 (408, "Hauteclere's Opus"),
 (410, "Tharja's Crystal Ball"),
 (412, "Tharja's Liver-and-Eel Pie"),
 (414, "Tharja's Essence"),
 (416, "Tharja's Hex's Scroll"),
 (418, "Olivia's Hair Band"),
 (420, "Olivia's Model Theater"),
 (422, "Olivia's Essence"),
 (424, "Olivia's Blade's Scroll"),
 (426, "Falchion's Opus"),
 (428, "Parallel Falchion's Opus"),
 (430, "Thoron's Opus"),
 (432, "Lissa's Axe's Opus"),
 (434, "Frederick's Axe's Opus"),
 (436, "Cordelia's Lance's Opus"),
 (1416, "Missiletainn's Opus"),
 (1418, "Tharja's Hex's Opus"),
 (1420, "Olivia's Blade's Opus"),
 (438, 'Master Seal'))
WEAPONS = {114: 'Hero Sword (S Rank)',
 115: 'Hero Lance (S Rank)',
 116: 'Hero Axe (S Rank)',
 117: 'Hero Bow (S Rank)',
 118: 'Hero Tome (S Rank)',
 119: 'Herostone (S Rank)',
 4: 'Brave Sword (A Rank)',
 26: 'Brave Lance (A Rank)',
 39: 'Brave Axe (A Rank)',
 50: 'Brave Bow (A Rank)',
 60: 'Brave Tome (A Rank)',
 71: 'Bravestone (A Rank)',
 3: 'Silver Sword (B Rank)',
 25: 'Silver Lance (B Rank)',
 38: 'Silver Axe (B Rank)',
 49: 'Silver Bow (B Rank)',
 59: 'Silver Tome(B Rank)',
 70: 'Silverstone (B Rank)',
 2: 'Steel Sword (C Rank)',
 24: 'Steel Lance (C Rank)',
 37: 'Steel Axe (C Rank)',
 48: 'Steel Bow (C Rank)',
 58: 'Steel Tome (C Rank)',
 69: 'Steelstone (C Rank)',
 1: 'Iron Sword (D Rank)',
 23: 'Iron Lance (D Rank)',
 36: 'Iron Axe (D Rank)',
 47: 'Iron Bow (D Rank)',
 57: 'Iron Tome (D Rank)',
 68: 'Ironstone(D Rank)',
 0: 'Bronze Sword (E Rank)',
 22: 'Bronze Lance (E Rank)',
 35: 'Bronze Axe (E Rank)',
 46: 'Bronze Bow (E Rank)',
 56: 'Bronze Tome (E Rank)',
 67: 'Bronzestone (E Rank)',
 5: 'Enliron (Rowan)',
 6: 'Facinna (Lianna)',
 7: 'Yato (Corrin)',
 8: 'Raijinto (Ryoma)',
 9: 'Siegfried (Xander)',
 10: 'Falchion (Chrom)',
 11: 'Parallel Falchion (Lucina)',
 12: 'Exalted Falchion (Marth)',
 14: 'Lady Sword (Celica)',
 15: 'Sol Katti (Lyn)',
 16: 'Missiletainn (Owain)',
 17: 'Wo Dao (Navarre)',
 111: "Chrom's Training Sword (Chrom amiibo)",
 123: "Olivia's Blade (Olivia)",
 27: "Hinoka's Spear (Hinoka)",
 28: "Oboro's Spear (Oboro)",
 29: "Cordelia's Lance (Cordelia)",
 30: 'Wing Spear (Caeda)',
 113: 'Blessed Lance (Azura)',
 40: "Camilla's Axe (Camilla)",
 41: "Lissa's Axe (Lissa)",
 42: "Frederick's Axe (Frederick)",
 122: 'Hauteclere (Minerva)',
 51: 'Fujin Yumi (Takumi)',
 52: 'Spellbane Yumi (Sakura)',
 53: "Niles's Bow (Niles)",
 54: "Anna's Bow (Anna)",
 61: 'Brynhildr (Leo)',
 62: 'Moonlight (Elise)',
 63: 'Thoron (Robin)',
 121: 'Aura (Linde)',
 124: "Tharja's Hex (Tharja)",
 72: 'Divinestone (Tiki)',
 112: "Tiki's Tear (Tiki amiibo)"}
SEALS = {0: 'Empty',
 255: 'Nothing',
 1: 'Strong I',
 2: 'Strong II',
 3: 'Strong III',
 4: 'Strong IV',
 5: 'Strong V',
 6: 'Strong VI',
 7: 'Rainstorm',
 8: 'Mountslayer (decrease weapon damage)',
 9: 'Wingslayer (decrease weapon damage)',
 10: 'Plateslayer (decrease weapon damage)',
 11: 'Dracoslayer (decrease weapon damage)',
 12: 'Beastslayer (decrease weapon damage)',
 13: 'Mountslayer (weapon damage stays the same)',
 14: 'Wingslayer (weapon damage stays the same)',
 15: 'Plateslayer (weapon damage stays the same)',
 16: 'Dracoslayer (weapon damage stays the same)',
 17: 'Beastslayer (weapon damage stays the same)',
 18: 'Rampager (weapon damage stays the same)',
 19: 'Divining',
 20: 'Power Up',
 21: 'First Class',
 22: 'Healer',
 23: 'Healing Gift',
 24: 'Warrior Gift',
 25: 'Awaken Gift',
 26: 'Triangle+',
 27: 'Pair Up+',
 28: 'Critical+',
 29: 'Warrior+',
 30: 'Health+',
 31: 'Desperate+',
 32: 'Antitriangle',
 33: 'Topsy-Turvy',
 34: 'True Power',
 35: 'Strike Rate+',
 36: 'All Stats+',
 37: 'Armor Strike',
 38: 'Fury Builder',
 39: 'Swordbreaker',
 40: 'Lancebreaker',
 41: 'Axebreaker',
 42: 'Bowbreaker',
 43: 'Tomebreaker',
 44: 'Stonebreaker',
 45: 'Clawbreaker',
 46: 'Divine Favor',
 47: 'Critical Focus',
 48: 'Anti-air Focus',
 49: 'Genpeer',
 50: 'Gencross',
 51: 'Statflip',
 52: 'Bolster',
 53: 'Acceleration',
 54: 'Amped',
 55: 'Legendary'}
CHARACTERS = ('Rowan',
 'Lianna',
 'Corrin',
 'Ryoma',
 'Hinoka',
 'Takumi',
 'Sakura',
 'Oboro',
 'Xander',
 'Camilla',
 'Leo',
 'Elise',
 'Niles',
 'Chrom',
 'Lucina',
 'Robin',
 'Lissa',
 'Frederick',
 'Cordelia',
 'Owain',
 'Anna',
 'Marth',
 'Caeda',
 'Navarre',
 'Tiki',
 'Celica',
 'Lyn',
 'Azura',
 'Linde',
 'Minerva',
 'Olivia',
 'Tharja')
