"""Factual DW6 PC identity/name maps, independently used by this implementation.

Names and numeric identities are documented by cnopt's public research, commit
f2152f67b031091a0268154203d25fa9f65d2664. No upstream parser implementation,
images, bundled dependencies or game assets are included.
"""

OFFICER_NAMES = (
    'Xiahou Dun',
    'Dian Wei',
    'Sima Yi',
    'Zhang Liao',
    'Cao Cao',
    'Zhou Yu',
    'Lu Xun',
    'Sun Shang Xiang',
    'Gan Ning',
    'Sun Jian',
    'Zhao Yun',
    'Guan Yu',
    'Zhang Fei',
    'Zhuge Liang',
    'Liu Bei',
    'Diao Chan',
    'Lu Bu',
    'Xu Zhu',
    'Xiahou Yuan',
    'Xu Huang',
    'Zhang He',
    'Cao Ren',
    'Cao Pi',
    'Taishi Ci',
    'Lu Meng',
    'Huang Gai',
    'Zhou Tai',
    'Ling Tong',
    'Sun Ce',
    'Sun Quan',
    'Ma Chao',
    'Huang Zhong',
    'Wei Yan',
    'Guan Ping',
    'Pang Tong',
    'Dong Zhuo',
    'Yuan Shao',
    'Zhang Jiao',
    'Zhen Ji',
    'Xiao Qiao',
    'Yue Ying',
)

WEAPON_NAMES = (
    'Rock Crusher',
    'Wave Breaker',
    'Thundersmash',
    'Violent Soul Flail',
    "Lion's Head Flail",
    'Beserker Flail',
    ' Eradication Claws',
    'Anguish Claws',
    'Necrosis Claws',
    'Twin Vipers',
    'Twin Dragons',
    'Twin Eagles',
    'Sword of Heaven',
    'Blue Blade',
    'Seven Star Sword',
    'Red Dusk',
    'Dark Night',
    'Scarlet Dawn',
    'Silver Swallow',
    'Blue Falcon',
    'Jade Warbler',
    'Madder Rose',
    'Wisteria Breeze',
    'Lotus Bow',
    'Crescent Moon',
    'Dancing Dragon',
    'Wing Blade',
    'Elder Sword',
    'Nine Hook Sword',
    'Golden Pheonix',
    'Dragon Spike',
    'Dragon Fang',
    'Dragon Talon',
    'Blue Dragon',
    'Black Dragon',
    'White Dragon',
    'Serpent Blade',
    'Python Blade',
    'Viper Blade',
    'Brilliance',
    'Distinction',
    'Enlightenment',
    'Strength and Virtue',
    'Heaven and Earth',
    'Yin and Yang',
    'Moonflower',
    'Dewflower',
    'Rainflower',
    'Sky Piercer',
    'Demon Bane',
    'Heron Blade Halberd',
    'Bone Crusher',
    'Chaos Crusher',
    'Whirlwind Crusher',
    'Heavens Destroyer',
    'Heavens Smasher',
    'Heavens Cutter',
    'Destroyer',
    'Annihilator',
    'Obliterator',
    'Splendor',
    'Mystery',
    'Ostentation',
    'Phoenix Wing',
    'Dragon Scale',
    'Tortoise Bite',
    'Havoc',
    'Mayhem',
    'Chaos',
    'Rage Trident',
    'Savage Trident',
    'Tsunami Trident',
    'Valor',
    'Spirit',
    'Courage',
    'River Slicer',
    'Mountain Breaker',
    'Sky Lasher',
    'Flashstrike',
    'Dawnstrike',
    'Duskstrike',
    'Flying Nimbus',
    'Rising Nimbus',
    'Lofting Nimbus',
    'Tryant Strike',
    'Glimmer Strike',
    'Stoic Strike',
    "Dragon's Might",
    "Heaven's Might",
    "Tiatan's Might",
    'Ironhorse Glaive',
    'Dragonrun Glaive',
    'Warsteed Glaive',
    'Immortal Blade',
    'Battle Master Blade',
    'Princeps Blade',
    'The Awakener',
    'Bone Splitter',
    'Stormhowl',
    'Blue Dragon Ji',
    'Black Dragon Ji',
    'White Dragon Ji',
    'Firestorm Staff',
    'Blizzard Staff',
    'Typhoon Staff',
    'Wizard Club',
    'Magus Club',
    'Augur Club',
    'Sword of Kings',
    'Sword of Severity',
    'North Star Sword',
    'Blaze Staff',
    'Blight Staff',
    'Judgement Staff',
    'Allure',
    'Charm',
    'Seduction',
    'True',
    'True Beauty',
    'True Luster',
    'Emerald Dew',
    'Emerald Veil',
    'Emerald Mist',
)

ELEMENT_NAMES = ('Fire', 'Ice', 'Lightning', 'None')
